:white_check_mark:  add test for addSpotifyPlaylistHandler
kanko-dori/favox pull request #125
Opened 2020-12-12 07:07 UTC by onsd

## WHY

https://github.com/kanko-dori/favox/pull/124
refactoring で他に影響していたが気づけなかった

## WHAT

テストを書いた

2020-12-12 09:27 UTC, ssssota commented on src/backend/lib/firestore.ts
> +export const getSpotifyUserByUid = async (uid: string): Promise<User> => {
中身promiseチェーンで書くならnew Promiseする必要ないのでは?

2020-12-12 09:27 UTC, ssssota commented on src/backend/lib/firestore.ts
> +          reject();
`reject();`は`throw;`くらいわけわからんので`reject(new Error('ID is not found'));`とかエラー理由を書いてあげてください

2020-12-12 09:27 UTC, ssssota commented on src/backend/test/handlers.test.ts
> +  it('successfully finished', async () => {
これ、mockが呼ばれるかみたいなテスト名にすべきだし、
mockは呼ばれるからテストしても仕方ないし、
読んだ結果がちゃんとDBに格納されてるかみたいなのが大事なのでは

2020-12-12 09:30 UTC, onsd commented on src/backend/test/handlers.test.ts
> +  it('successfully finished', async () => {
DBに格納されるかどうかのテストはしたいけど、Firestoreをmockする必要があって後回しにしてる

意図としては、tracksの型を変えたときにこういったテストがあれば気づけたかもしれないなって思って書いた

2020-12-12 09:32 UTC, ssssota commented on src/backend/test/handlers.test.ts
> +  it('successfully finished', async () => {
それなら、テスト名でスコープを明らかにすべきですね
![image](https://user-images.githubusercontent.com/15074382/101980398-5600d700-3ca8-11eb-98af-ad1415e9272f.png)

2020-12-12 09:32 UTC, ssssota requested changes
テスト名がテスト内容を示していない

2020-12-12 09:34 UTC, ssssota commented on src/backend/test/handlers.test.ts
> +  it('successfully finished', async () => {
テスト名を英語で書くときは大体`if('should ~~`であるべき

2020-12-26 12:32 UTC, ssssota approved these changes
lgtm

2020-12-26 13:48 UTC, merged