Spotify APIを使ってプレイリストの情報を取得する
kanko-dori/favox pull request #67
Opened 2020-11-02 17:43 UTC by watamoko

## WHY
issue #56

## WHAT
- spotify-web-api-nodeを使用して、Spotify-apiからプレイリストを取得する関数を作成しました。
- 正しいplaylistIdからPlaylistを取得できるテストを作成しました。

2020-11-02 17:45 UTC, onsd commented
TODO
- [ ] token を firestore などから取得するようにする

2020-11-02 17:46 UTC, ssssota commented
ref #64

2020-11-03 10:02 UTC, ssssota commented on src/backend/lib/types.d.ts
> +/// <reference types="spotify-api" />
これ、tsconfigの`types`とかにいれるのが正解っぽい

2020-11-03 10:02 UTC, ssssota commented on src/backend/lib/test/getPlaylist.test.ts
> +    expect(getSpotifyPlaylist('watamokosan')).rejects.toThrow('Invalid playlist Id');
```suggestion
    expect(getSpotifyPlaylist('INVALID_PLAYLIST_ID')).rejects.toThrow('Invalid playlist Id');
```
とかの方が可読性高そう

2020-11-03 10:02 UTC, ssssota commented on src/backend/lib/getPlaylist.ts
> +    throw new Error('invalid response');
```suggestion
    throw new Error('Invalid response');
```

2020-11-14 16:02 UTC, onsd requested changes

2020-11-14 16:02 UTC, onsd commented on src/backend/lib/test/getPlaylist.test.ts
> +  it('不正なplaylistIdからPlaylistを取得できない', async () => {
`不正なplaylistIdからPlaylistを取得できない` というテストは SpotifyWebAPI でやってるはずなので、statusCode が 200 でないときのテストに変更したほうが良いと思います

2020-12-06 12:03 UTC, onsd commented
とりあえず close

2020-12-06 12:03 UTC, closed without merging